# Generated by Django 2.1.7 on 2020-06-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=254, unique=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dProfile',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('lno', models.CharField(max_length=100, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ph', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=150)),
                ('exp', models.DateField()),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='udetails',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioapp.dProfile'),
        ),
    ]
